server:
  port: 8042

spring.cloud.stream:
  function:
    definition: consumer
  bindings:
    consumer-in-0:
      destination: order-created
  kafka:
    binder:
      replication-factor: 1
      brokers: localhost:9092
      auto-create-topics: true
