server:
  port: 8042

spring.cloud.stream:
  function:
    definition: processor
  bindings:
    processor-in-0:
      destination: order-created
    processor-out-0:
      destination: order-updated
  kafka:
    binder:
      replication-factor: 1
      brokers: localhost:9092
      auto-create-topics: true
